---
label: Global Site Config
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: none
  label: None
  description: An empty var, used so the site params section will function
  hidden: true
